import AchievementCard from '../components/AchievementCard'
import CertificateCard from '../components/CertificateCard'
import SectionHeading from '../components/SectionHeading'
import scholarsLeadershipCamp from '../assets/certificates/ScholarsLeadershipCamp.jpg'
import yugtoCertificate from '../assets/certificates/yugto.png'
import tugatogCertificate from '../assets/certificates/Tugatog.jpg'
import hackathonCertificate from '../assets/certificates/hackathon.png'

export default function Achievements(){return <><section className="border-b border-line bg-white py-14 sm:py-20"><div className="container"><p className="kicker">Recognition & affiliations</p><h1 className="display mt-4 text-5xl font-semibold sm:text-6xl">Achievements</h1><p className="prose-copy mt-6">Academic, regional, and DOST-related involvement.</p></div></section><section className="section"><div className="container"><SectionHeading eyebrow="Highlights" title="Achievements and DOST"/><div className="grid gap-4 md:grid-cols-3"><AchievementCard meta="Hack4AProgress 2026 CALABARZON" title="Winner" detail="Project: AgriWise"/><AchievementCard meta="START-DOST · 2026" title="Selected Regional Representative" detail="Regional representation role."/><AchievementCard meta="DOST-SEI" title="Undergraduate Scholar" detail="DOST-SEI Undergraduate Scholar."/></div><div className="mt-16"><SectionHeading eyebrow="Affiliations" title="DOST involvement"/><div className="grid gap-4 md:grid-cols-3"><AchievementCard meta="Scholarship" title="DOST-SEI Undergraduate Scholar" detail="Academic scholarship affiliation."/><AchievementCard meta="2026" title="Regional Representative" detail="START-DOST"/><AchievementCard meta="AY 2025–2026" title="Finance Committee" detail="LSPU SCC DOST Scholars’ Guild"/></div></div><div className="mt-16"><SectionHeading eyebrow="Training & programs" title="Certificates gallery" copy="View supporting certificate documentation for training programs and recognition."/><div className="grid gap-4 md:grid-cols-3"><CertificateCard title="Hack4AProgress 2026" organization="DOST CALABARZON" detail="Certificate of Recognition · Top 3 Winner, EverForge" image={hackathonCertificate} documentUrl={hackathonCertificate}/><CertificateCard title="DOST CALABARZON Scholars’ Leadership Camp" organization="DOST CALABARZON" detail="Participant · May 2026" image={scholarsLeadershipCamp} documentUrl={scholarsLeadershipCamp}/><CertificateCard title="YUGTO 2024" organization="DOST Regional Patriot Council CALABARZON" detail="Participant · November 25, 2024" image={yugtoCertificate} documentUrl={yugtoCertificate}/><CertificateCard title="LSPU Tugatog Leadership Training and Workshop 2.0" organization="LSPU" detail="Participant · October 29, 2024" image={tugatogCertificate} documentUrl={tugatogCertificate}/></div></div></div></section></>}
