import { ArrowRight, Code2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { focusAreas, projects, skills } from '../data/portfolio'
import SectionHeading from '../components/SectionHeading'
import ProjectCard from '../components/ProjectCard'
import TechBadge from '../components/TechBadge'
import CvDownload from '../components/CvDownload'

export default function Home() { return <>
  <section className="border-b border-line bg-white"><div className="container grid gap-10 py-16 sm:py-24 lg:grid-cols-[1.35fr_.65fr] lg:items-end"><div className="enter"><p className="kicker">Computer Science · DOST-SEI Scholar</p><h1 className="display mt-5 max-w-4xl text-5xl font-semibold sm:text-7xl">Ross Cedric<br/>Nazareno</h1><p className="mt-6 text-lg font-medium text-teal">Full-Stack Software Engineer<br/>Intelligent Systems · Applied Software Development</p><p className="prose-copy mt-5">Fourth-year Computer Science student and DOST-SEI Scholar building full-stack software systems across frontend, backend, databases, APIs, deployment, and intelligent system integration.</p><p className="prose-copy mt-3">My work includes real-time traffic systems, community platforms, agricultural decision-support software, computer vision, forecasting, and simulation.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/projects" className="button-primary inline-flex items-center gap-2 rounded-sm px-4 py-3 text-sm font-semibold">View projects <ArrowRight size={17}/></Link><CvDownload/><a href="https://github.com/0ced0" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-3 py-3 text-sm font-semibold text-muted hover:text-teal"><Code2 size={17}/> GitHub</a></div></div><aside className="border-l border-line pl-5 lg:pb-2"><p className="text-sm font-semibold">Specialization</p><p className="mt-3 text-sm leading-6 text-muted">Intelligent systems that integrate real-time processing, data workflows, forecasting, simulation, and practical software deployment.</p><Link to="/about" className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-teal">More about my work <ArrowRight size={15}/></Link></aside></div></section>
  <section className="section"><div className="container"><SectionHeading eyebrow="Areas of focus" title="Software engineering, with intelligent systems in context."/><div className="grid border-l border-t border-line sm:grid-cols-2 lg:grid-cols-3">{focusAreas.map((area,i)=><div key={area} className="border-b border-r border-line bg-white p-5"><span className="text-sm text-teal">0{i+1}</span><p className="mt-8 font-semibold">{area}</p></div>)}</div></div></section>
  <section className="section"><div className="container"><SectionHeading eyebrow="Selected work" title="Complete systems built for real use." copy="Full-stack platforms, data-intensive decision support, and intelligent-system integrations. Each case study documents the system architecture, scope, and current status." action={<Link to="/projects" className="text-sm font-semibold text-teal">All projects →</Link>}/><ProjectCard project={projects.easyflow} slug="easyflow"/><ProjectCard project={projects.cospheria} slug="cospheria"/><ProjectCard project={projects.agriwise} slug="agriwise"/></div></section>
  <section className="section bg-white"><div className="container"><SectionHeading eyebrow="Technical foundation" title="Continuous Learning"/>{Object.entries(skills).map(([group,categories])=><div key={group} className={`mb-12 last:mb-0 ${group==='Intelligent Systems'?'mt-16':''}`}><h3 className="mb-5 text-xl font-semibold tracking-tight text-ink">{group}</h3><div className="grid gap-x-10 gap-y-7 md:grid-cols-2">{Object.entries(categories).map(([category,items])=><div key={category} className="border-t border-line pt-4"><h4 className="text-sm font-semibold">{category}</h4><div className="mt-3 flex flex-wrap gap-2">{items.map(x=><TechBadge key={x}>{x}</TechBadge>)}</div></div>)}</div></div>)}</div></section>
</> }
