import { Link, useParams } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { projects } from '../data/portfolio'
import ProjectHero from '../components/ProjectHero'
import SectionHeading from '../components/SectionHeading'
import ArchitectureDiagram from '../components/ArchitectureDiagram'
import ImageGallery from '../components/ImageGallery'
import TechBadge from '../components/TechBadge'
export default function ProjectCaseStudy(){const {slug}=useParams();const project=projects[slug]; if(!project) return <section className="section"><div className="container"><h1 className="text-3xl font-semibold">Project not found</h1><Link className="mt-5 inline-block text-teal" to="/projects">Back to projects</Link></div></section>;const hasScreenshots=project.images.some(item=>typeof item!=='string');return <><ProjectHero project={project}/><section className="section"><div className="container"><Link className="mb-10 inline-flex items-center gap-2 text-sm font-semibold text-teal" to="/projects"><ArrowLeft size={16}/> All projects</Link><div className="max-w-3xl"><SectionHeading eyebrow="Overview" title="Project context" copy={project.summary}/></div>{project.pipeline.length>0&&<ArchitectureDiagram steps={project.pipeline} title={slug==='agriwise'?'Data and decision-support flow':'System architecture'}/>}<div className="mt-16 grid gap-x-16 gap-y-12 lg:grid-cols-[minmax(0,1fr)_17rem]"><div className="space-y-12">{project.sections.map(([heading,copy])=><section key={heading}><h2 className="text-2xl font-semibold tracking-tight">{heading}</h2><p className="prose-copy mt-4">{copy}</p></section>)}</div><aside className="h-fit border-t border-line pt-4 lg:sticky lg:top-24"><p className="text-sm font-semibold">Tech stack</p><div className="mt-4 flex flex-wrap gap-2">{project.stack.map(x=><TechBadge key={x}>{x}</TechBadge>)}</div></aside></div><section className="mt-20"><SectionHeading eyebrow="Visual documentation" title="Screenshots" copy={hasScreenshots?`Selected ${project.title} system views and technical outputs.`:'Project visual assets will be added here as they become appropriate to share.'}/><ImageGallery items={project.images}/></section></div></section></>}
